#!/usr/bin/env bash
# This script displays numbers from 1 to 20 with specific translations for 4, 9, and 17

counter=1
while [ "$counter" -le 20 ]
do
    case "$counter" in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
            echo "$counter"
            ;;
    esac
    counter=$((counter + 1))
done
