#!/usr/bin/env bash
# This script displays numbers 1 to 20 with cultural superstitions using case

counter=1
while [ "$counter" -le 20 ]
do
    case "$counter" in
        4)
            echo "4"
            echo "bad luck from China"
            ;;
        9)
            echo "9"
            echo "bad luck from Japan"
            ;;
        17)
            echo "17"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$counter"
            ;;
    case
    counter=$((counter + 1))
done
