#!/usr/bin/env bash
# This script creates a PID file, handles custom signals, and cleans up upon exit

# Write the current script PID to the target destination file
echo "$$" > /var/run/myscript.pid

# Function to execute on SIGTERM shutdown cleanup
clean_exit() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 0
}

# Function to execute on SIGQUIT shutdown cleanup
quit_exit() {
    rm -f /var/run/myscript.pid
    exit 0
}

# Assign signal handlers
trap 'clean_exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'quit_exit' SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
